// components/react/components/button.tsx
import { ark } from '@ark-ui/react/factory'
import type { ComponentProps } from 'react'
import { styled } from '~/styled-system///jsx'
import { buttonRecipe } from '~/styled-system///recipes'

export const Button = styled(ark.button, buttonRecipe)
export interface ButtonProps extends ComponentProps<typeof Button> {}

// components/solid/components/button.tsx
import { ark } from "@ark-ui/solid";
import type { ComponentProps } from "solid-js";
import { styled } from "~/styled-system/jsx";
import { button } from "~/styled-system/recipes";

export const Button = styled(ark.button, button);
export interface ButtonProps extends ComponentProps<typeof Button> {}
